[package]
name = "ftlsavemanager"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "*"
static_vcruntime = "1.3"
glium = { version = "0.29", default-features = true }
image = "0.23"
imgui = "0.7"
imgui-glium-renderer = "0.7"
imgui-winit-support = "0.7"

# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "target-feature=+crt-static"]

# [target.i686-pc-windows-msvc]
# rustflags = ["-C", "target-feature=+crt-static"]